defmodule Sandbox.Category do
  @moduledoc """
  Category module, provide matching function for building transaction details.category.
  """
  def category("Uber"), do: "transport"
  def category("Lyft"), do: "transport"
  def category("Uber Eats"), do: "groceries"
  def category("Five Guys"), do: "dining"
  def category("In-N-Out Burger"), do: "dining"
  def category("Chick-Fil-A"), do: "dining"
  def category("Apple"), do: "software"
  def category("Amazon"), do: "software"
  def category("Walmart"), do: "groceries"
  def category("Target"), do: "electronics"
  def category("Hotel Tonight"), do: "accommodation"
  def category("Misson Ceviche"), do: "dining"
  def category("Caltrain"), do: "transport"
  def category("Wingstop"), do: "dining"
  def category("Slim Chickens"), do: "dining"
  def category("CVS"), do: "health"
  def category("Duane Reade"), do: "health"
  def category("Walgreens"), do: "health"
  def category("McDonald's"), do: "dining"
  def category("Burger King"), do: "dining"
  def category("KFC"), do: "dining"
  def category("Popeye's"), do: "dining"
  def category("Shake Shack"), do: "dining"
  def category("Lowe's"), do: "home"
  def category("Costco"), do: "groceries"
  def category("Kroger"), do: "shopping"
  def category("iTunes"), do: "software"
  def category("Spotify"), do: "software"
  def category("Best Buy"), do: "software"
  def category("TJ Maxx"), do: "groceries"
  def category("Aldi"), do: "groceries"
  def category("Macy's"), do: "health"
  def category("H.E. Butt"), do: "shopping"
  def category("Dollar Tree"), do: "shopping"
  def category("Verizon Wireless"), do: "phone"
  def category("Sprint PCS"), do: "phone"
  def category("Starbucks"), do: "bar"
  def category("7-Eleven"), do: "shopping"
  def category("AT&T Wireless"), do: "phone"
  def category("Rite Aid"), do: "health"
  def category("Nordstrom"), do: "loan"
  def category("Ross"), do: "general"
  def category("Bed, Bath & Beyond"), do: "service"
  def category("J.C. Penney"), do: "shopping"
  def category("Subway"), do: "dining"
  def category("O'Reilly"), do: "dining"
  def category("Wendy's"), do: "dining"
  def category("T-Mobile"), do: "phone"
  def category("Petsmart"), do: "shopping"
  def category("Dick's Sporting Goods"), do: "sport"
  def category("Sears"), do: "electronics"
  def category("Staples"), do: "office"
  def category("Domino's Pizza"), do: "dining"
  def category("Papa John's"), do: "dining"
  def category("IKEA"), do: "electronics"
  def category("Office Depot"), do: "shopping"
  def category("Foot Locker"), do: "shopping"
  def category("Lids"), do: "shopping"
  def category("GameStop"), do: "shopping"
  def category("Panera"), do: "dining"
  def category("Williams-Sonoma"), do: "home"
  def category("Saks Fifth Avenue"), do: "home"
  def category("Chipotle Mexican Grill"), do: "dining"
  def category("Neiman Marcus"), do: "loan"
  def category("Jack In The Box"), do: "dining"
  def category("Sonic"), do: "entertainment"
  def category("Shell"), do: "fuel"
  def category(_), do: "unknown"
end
